CREATE TABLE COUNTRY(
	ID serial PRIMARY KEY,
	NAME VARCHAR(50)
);


CREATE TABLE PRESIDENTS(
	ID serial PRIMARY KEY,
	NAME VARCHAR(50),
	AGE int
);

CREATE TABLE COUNTRY_PRESIDENTS(
	id serial PRIMARY KEY,
	COUNTRY_ID int references COUNTRY(id) unique,
    PRESIDENTS_ID int references PRESIDENTS(id) unique
);